spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LMS-for-vacancy?currentSchema=LMS
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
