spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LMS-for-vacancy?currentSchema=LMS
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
jwt:
  secret:
    key: '5267556B58703273357638782F413F4428472B4B6250655368566D5971337436'
  expiry:
    in:
      minutes: 4320 #3 days (change it)